//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istocpos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisID { get; set; }
        public Nullable<int> IslemBo { get; set; }
        public string UrunAd { get; set; }
        public string Barkod { get; set; }
        public string Grup { get; set; }
        public string Birim { get; set; }
        public Nullable<double> AlisFiyat { get; set; }
        public Nullable<double> Satis1 { get; set; }
        public Nullable<double> Satis2 { get; set; }
        public Nullable<double> Satis3 { get; set; }
        public Nullable<double> Satis4 { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<double> Toplam { get; set; }
        public Nullable<double> KdvTutar { get; set; }
        public string OdemeSekli { get; set; }
        public Nullable<bool> Iade { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kullanici { get; set; }
    }
}
